//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextAnalyzer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTextAnalyzerEntities : DbContext
    {
        public DBTextAnalyzerEntities()
            : base("name=DBTextAnalyzerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Phras> Phrases { get; set; }
        public DbSet<PhraseWord> PhraseWords { get; set; }
        public DbSet<TextLog> TextLogs { get; set; }
        public DbSet<Word> Words { get; set; }
    }
}
